source 'https://github.com/VeryLoveLoli/CocoaPodsSource.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!

target 'CCProjectTemplateTest' do

    pod 'JSONValue',    '1.0-master'
    pod 'XMLValue',     '1.0-master'
    pod 'TEA',          '1.0-master'
    pod 'Network',      '1.0-master'
    pod 'DragLoad',     '1.0-master'
    pod 'Prompt',       '1.0-master'
end

